### ISSUE TITLE
Preloaded Sample Data does not match Image in User Guide

### ISSUE THREAD

**Issue by valhrd** [AY2425S1-CS2103T-W14-2/tp#121]
## Preloaded sample data
![image](https://github.com/user-attachments/assets/97f6b17f-375b-45b8-9ec7-25623632bb4b)

## User Guide image
![image](https://github.com/user-attachments/assets/d3de3da2-15f2-4170-b9ca-c167628b3f2c)

A very minor concern but since the sample data presented does not match, should we change to fit it or is it fine as it is?

**Comment by DiegoTheExplorar** [comment]
Will be adding in sample addressbook
