### ISSUE TITLE
AdvFilter does not show an error to the user when invalid operator is provided 

### ISSUE THREAD

**Issue by appleshill** [AY2425S1-CS2103T-W14-2/tp#131]
<img width="740" alt="Screenshot 2024-10-27 at 5 59 21 PM" src="https://github.com/user-attachments/assets/74a2c359-6926-4964-83ea-bbc8cf3bad6e">
Instead the error can only be seen in the terminal.

**Comment by frymash** [comment]
Could possibly address this issue with the same error-catching mechanism that catches invalid command formats

**Comment by DiegoTheExplorar** [comment]
Add an error
