### ISSUE TITLE
Filter does not work with tags that have a value

### ISSUE THREAD

**Issue by appleshill** [AY2425S1-CS2103T-W14-2/tp#132]
<img width="740" alt="Screenshot 2024-10-27 at 6 21 24 PM" src="https://github.com/user-attachments/assets/cf56f566-4057-4e75-a23a-05f4bbad9581">
<img width="740" alt="Screenshot 2024-10-27 at 6 21 31 PM" src="https://github.com/user-attachments/assets/4b2c1822-6f1d-4cfd-89aa-bf23df5af598">

**Comment by frymash** [comment]
Indicate this in the UG under "Known issues"
