### ISSUE TITLE
Tag key/value matching in filter and advfilter

### ISSUE THREAD

**Issue by appleshill** [AY2425S1-CS2103T-W14-2/tp#140]
> Case sensitivity: In general, case sensitivity of something should follow the case sensitivity of the real world entity it represents e.g., as person names are not case-sensitive in the real world, they shouldn't be case-sensitive in the app either. The same applies for search keywords. Incorrect case sensitivity can be considered a FeatureFlaw

Since tags represent some miscellaneous information that might need to be compared between different contacts, it could be argued that they should not be case sensitive – for instance, the tag 'friend' and 'Friend' would be the same. Hence, filter and advfilter could ignore cases for filtering by tags.

**Comment by DiegoTheExplorar** [comment]
Same issue
