### ISSUE TITLE
Case sensitive tag

### ISSUE THREAD

**Issue by DiegoTheExplorar** [AY2425S1-CS2103T-W14-2/tp#146]
![image](https://github.com/user-attachments/assets/02d0c29c-691d-45bd-85e2-3660426386e1)

Tags are case sensitive

**Comment by DiegoTheExplorar** [comment]
Leave it alone. BUT mention in UG/DG that filter and advfilter is case INsensititve

**Comment by RyanWarwick** [comment]
Sort will be case INsensitive as well
