### ISSUE TITLE
Minor UG and DG formatting issues

### ISSUE THREAD

**Issue by appleshill** [AY2425S1-CS2103T-W14-2/tp#218]
![Screenshot 2024-11-07 at 10 25 31 AM](https://github.com/user-attachments/assets/452bce35-d919-47c1-9d10-445e43a168c8)
![Screenshot 2024-11-07 at 10 26 39 AM](https://github.com/user-attachments/assets/822fde36-9d20-4401-9716-f0b4e2a0c77d)
![Screenshot 2024-11-07 at 10 26 54 AM](https://github.com/user-attachments/assets/e0f1e494-a82c-44ae-a97d-a50550e4ef9b)

**Comment by frymash** [comment]
From the UG: the screenshot for `help` is outdated.
 
<img width="844" alt="Screenshot 2024-11-07 at 7 51 16 PM" src="https://github.com/user-attachments/assets/3f7ee7a0-730e-412f-8bfe-1c4ae59def14">

**Comment by appleshill** [comment]
The help issue should be under updating screenshots.
