### ISSUE TITLE
[PE-D][Tester E] Advfilter incorrect documentation in user gude

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W14-2/tp#273]
From the user guide, it seems that `advfilter` takes in optional parameters:

![image.png](https://raw.githubusercontent.com/vinceg4/ped/main/files/4449782d-18af-4ed9-8453-113cdc27bfb1.png)
However, this is not the case as seen in the application usage message.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: vinceg4/ped#8

**Comment by RyanWarwick** [comment]
#276
