### ISSUE TITLE
[PE-D][Tester A] Advanced filter does not work as intended, searching via `=`, `>=`, `>`, `<` or `<=` returns profiles with tags with no values

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-2/tp#277]
![image.png](https://raw.githubusercontent.com/SeanFoongjt/ped/main/files/b082bdbe-4bed-4cd7-90cb-2fcf27bb7886.png)

Steps to reproduce:
1. `add` two valid profiles that have the same tag name but one with value and one without, `t\neighbours` and `t\neighbours:5`
2. Do an advanced filter for `t\neighbours = 5`

Expected:
When searching via the `=` operator in advanced filter, only profiles with the corresponding tags and exactly the corresponding value shows up in the list.

Actual:
Profiles with the corresponding tags and values show up in the list, but profiles with the corresponding tags and no values also show up in the list.

Note:
The same bug applies to `>=`, `>`, `<` and `<=`

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: SeanFoongjt/ped#14

**Comment by appleshill** [comment]
#253 #275

**Comment by RyanWarwick** [comment]
#275
#253
