### ISSUE TITLE
[PE-D][Tester A] `find` and `filter` are confusing due to different usage methods

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-2/tp#280]
![image.png](https://raw.githubusercontent.com/SeanFoongjt/ped/main/files/86510001-1c3a-4cc4-9b64-8befacf079d1.png)

![image.png](https://raw.githubusercontent.com/SeanFoongjt/ped/main/files/dac57ce9-1805-498c-8ae7-338b451f9a12.png)

Specifically, filter by name can find partial names but cannot find names when the parameters are rearranged whereas find by name can only find full words in names but can find them when the parameters are rearranged. This could cause the user to be confused when they want to use the features.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: SeanFoongjt/ped#15

**Comment by RyanWarwick** [comment]
Find searches s.t. ```Hans Bo``` and ```Bo Hans``` returns the same result. A general, OR-inclusive search.

Filter however, is a regex-based, AND-inclusive search for both name and tags.
