### ISSUE TITLE
t\TAG should not be optional in UG

### ISSUE THREAD

**Issue by appleshill** [AY2425S1-CS2103T-W14-2/tp#288]
![Screenshot 2024-11-09 at 4 10 04 PM](https://github.com/user-attachments/assets/e5a5b5e6-f2c6-4d2f-91b9-ff46e0adfb70)

**Comment by appleshill** [comment]
Related to #252

**Comment by frymash** [comment]
`advfilter`'s command template and in-app usage guide contain incorrect information on the command format. The format should be `advfilter t\TAG [OPERATOR] [VALUE]`.

<img width="732" alt="Screenshot 2024-11-09 at 4 12 00 PM" src="https://github.com/user-attachments/assets/c7daa7be-e4e7-463d-8343-74562e035fae">
