### ISSUE TITLE
Add Sort

### ISSUE THREAD

**Issue by DiegoTheExplorar** [AY2425S1-CS2103T-W14-2/tp#41]
### Purpose
Allows users to sort their contact list based on specific tag values.

### Command format
`sort t/TAG`

### Example commands
- `sort t/client`

#### Tag
- Acceptable values: Tag key must exist
- Error handling: If the tag does not exist, display: "Tag not found: Please provide an existing tag."

### Outputs
- Success: "Contacts sorted by [tag] tag."
- Failure: "Tag not found: [tag]."

**Comment by RyanWarwick** [comment]
Still WIP due to changes in fundamental JSON mapping changes for Tag class. Moving this to milestone v1.3 for now.

**Comment by RyanWarwick** [comment]
WIP due to breaking changes in underlying JSON mapping for Tag class. Moving to milestone v1.3 for now
