### ISSUE TITLE
Modify Autosave

### ISSUE THREAD

**Issue by DiegoTheExplorar** [AY2425S1-CS2103T-W14-2/tp#43]
# Feature: Auto-Save Changes to Text File (User-editable)

## Purpose
Automatically saves any changes made to contacts to a user-editable .txt file.

## Command format
No explicit command required; autosave is triggered after every change.

## Example actions
- Any change made (e.g., adding a contact, editing, deleting) will automatically save to `contacts.txt`.

## Parameters
None.

## Outputs
- Success: "Changes saved automatically."
- Failure: If an error occurs during saving, display: "Auto-save failed. Please check file permissions."

**Comment by valhrd** [comment]
Unneeded (already implemented by AB3 base version)
